---
- name: Create /etc/dovecot/dovecot.conf
  ansible.builtin.copy:
    src: dovecot.conf
    dest: /etc/dovecot/dovecot.conf
    owner: root
    group: root
    mode: 0644
    backup: yes

- name: Create /etc/dovecot/conf.d/10-master.conf
  ansible.builtin.copy:
    src: dovecot-10-master.conf
    dest: /etc/dovecot/conf.d/10-master.conf
    owner: root
    group: root
    mode: 0644
    backup: yes

- name: Create /etc/dovecot/conf.d/10-mail.conf
  ansible.builtin.copy:
    src: dovecot-10-mail.conf
    dest: /etc/dovecot/conf.d/10-mail.conf
    owner: root
    group: root
    mode: 0644
    backup: yes

- name: Create /etc/dovecot/conf.d/10-auth.conf
  ansible.builtin.copy:
    src: dovecot-10-auth.conf
    dest: /etc/dovecot/conf.d/10-auth.conf
    owner: root
    group: root
    mode: 0644
    backup: yes

- name: Create /etc/dovecot/dovecot-sql.conf.ext
  ansible.builtin.template:
    src: dovecot-sql.conf.ext.j2
    dest: /etc/dovecot/dovecot-sql.conf.ext
    owner: root
    group: root
    mode: 0644
    backup: yes

- name: Create /etc/dovecot/conf.d/10-ssl.conf
  ansible.builtin.template:
    src: dovecot-10-ssl.conf.j2
    dest: /etc/dovecot/conf.d/10-ssl.conf
    owner: root
    group: root
    mode: 0644
    backup: yes

- name: Create /etc/dovecot/conf.d/15-lda.conf
  ansible.builtin.copy:
    src: dovecot-15-lda.conf
    dest: /etc/dovecot/conf.d/15-lda.conf
    owner: root
    group: root
    mode: 0644
    backup: yes

# Fire it up.
- name: Restart Dovecot
  ansible.builtin.service:
    name: dovecot
    state: restarted
