---
- name: create minio bin_dir
  ansible.builtin.file:    
    path: "{{ minio__bin_dir }}"
    state: directory
    owner: "{{ minio__user }}"
    group: "{{ minio__group }}"
    mode: 0755

- name: Download the Minio server
  ansible.builtin.get_url:
    url: "https://dl.min.io/server/minio/release/linux-amd64/archive/minio.{{ minio__version }}"
    dest: "{{ minio__bin_dir }}/minio"
    owner: "{{ minio__user }}"
    group: "{{ minio__group }}"
    mode: 0755
  register: download_result
  until: download_result is succeeded
  retries: 5

- name: Create storage_dir
  ansible.builtin.file:
    path: "{{ minio__storage_dir }}"
    state: directory
    owner: "{{ minio__user }}"
    group: "{{ minio__group }}"
    mode: 0770

- name: Import environment file template
  ansible.builtin.template:
    src: minio.env.j2
    dest: /etc/default/minio
    owner: "{{ minio__user }}"
    group: "{{ minio__group }}"
    mode: 0770

- name: Create the Minio server service
  ansible.builtin.template:
    src: minio.service.j2
    dest: /etc/systemd/system/minio.service
    owner: root
    group: root
    force: true
  notify:
    - reload minio systemd
    - restart minio
