---
- name: Prepare Hosts
  hosts: k8s_cluster
  become: yes

  tasks:
    - name: Update and upgrade packages
      yum:
        name: '*'
        state: latest
        update_cache: true

    - name: Install packages
      yum:
        name:
          - vim
          - net-tools
          - curl
          - git
          - bash-completion
          - nfs-utils
          - python3
          - tar
          - rsyslog
          - wget
        state: latest