---
- name: Update and upgrade packages
  yum:
    name: '*'
    state: latest
    update_cache: true

- name: Install packages
  yum:
    name:
      - vim
      - net-tools
      - curl
      - git
      - bash-completion
      - nfs-utils
      - python3
      - tar
      - rsyslog
      - wget
    state: latest

- name: Disable NetworkManager
  service:
    name: NetworkManager
    state: stopped
    enabled: no

- name: Enable rsyslog
  service:
    name: rsyslog
    state: started
    enabled: yes

- name: Enable network service
  service:
    name: network
    state: started
    enabled: yes

- name: Stop Firewalld Service
  service:
    name: firewalld
    state: stopped
    enabled: false

- name: Check is swap enable
  shell: swapon
  register: swap_present
  changed_when: false
  ignore_errors: true

- name: If swap is enabled - disable it
  shell: swapoff -a
  when: swap_present.stdout != ""

- name: Disable swap in fstab
  replace:
    path: /etc/fstab
    regexp: '^([^#].*\s*swap\s*.*)$'
    replace: '# \1'

- name: Check Disable SELinux
  selinux:
    state: disabled
  register: selinux_ret

- name: Disable SELinux
  shell: serenforce 0
  when: selinux_ret.reboot_required