---
- name: Update and upgrade packages
  yum:
    name: '*'
    state: latest
    update_cache: true

- name: Install packages
  yum:
    name:
      - vim
      - net-tools
      - curl
      - git
      - bash-completion
      - nfs-utils
      - python3
      - tar
      - rsyslog
      - wget
    state: latest

- name: Disable NetworkManager
  service:
    name: NetworkManager
    state: stopped
    enabled: no

- name: Enable rsyslog
  service:
    name: rsyslog
    state: started
    enabled: yes

- name: Enable network service
  service:
    name: network
    state: started
    enabled: yes

- name: Stop Firewalld Service
  service:
    name: firewalld
    state: stopped
    enabled: false
  become: yes

- name: Check is swap enable
  shell: swapon
  register: swap_present
  changed_when: false
  ignore_errors: true